rom_path=roms
bios_dir=bios
lang=es
curvature=off
bloom=off
fullscreen=on
volume=100
window_scale=3
auto_save=off
muted=off
scanlines=on
bios=neogeo.zip:uni-bios_4_0.rom
ra_password=
ra_hardcore=off
diagnostic_dumps=off
gamepad=off
ra_token=
ra_username=