bios=neogeo.zip:sp-s2.sp1
bios_dir=bios
media_dir=media
lang=es
scanlines=on
curvature=off
bloom=on
fullscreen=off
aspect_ratio=4:3
rom_path=roms
volume=100
diagnostic_dumps=off
window_scale=3
auto_save=on
muted=off
gamepad=off
ra_token=
ra_password=
ra_username=
ra_hardcore=off
