rom_path=C:\Users\mabe8\Desktop\PROJECTOS_2026\NeoGeo_NeonEmu\roms
bios_dir=C:\Users\mabe8\Desktop\Nueva carpeta\bios
lang=es
curvature=off
bloom=off
fullscreen=on
volume=100
window_scale=3
auto_save=off
muted=off
scanlines=on
bios=neogeo.zip:uni-bios_4_0.rom
ra_password=XhJRt9Y9PMYGj4R
ra_hardcore=off
diagnostic_dumps=off
gamepad=off
ra_token=86dTzyW9CkenWvRI
ra_username=mabedeep